### ISSUE TITLE
"Release notes" for v0.6.0?

### ISSUE THREAD

**Issue by memark** [normartin/ts-retry-promise#15]
On _npm_ there is version _v0.6.0_, but it's absent under _Releases_. What was changed in this version?

**Comment by normartin** [comment]
Hey Magnus,
you are right I added a tag and Github release. (Git history on master is a bit unclean because I missed to stash when merging the feature).

Any suggestions (reference projects) for an simple automated NPM release process using Github Actions?

**Comment by normartin** [comment]
1. Created automated release process using Github Actions: #16 
2. Disabled merge into master

What do you think?

**Comment by memark** [comment]
Thanks for the quick response. I approved and added some comments.

**Comment by normartin** [comment]
Thanks for looking into this!
