### ISSUE TITLE
No timeout?

### ISSUE THREAD

**Issue by ftzi** [normartin/ts-retry-promise#27]
Hi, timeout defaults to 60000ms. It always uses setTimeout, so even if setting a very big number, setTimeout will be used.

I use React Native, and it complains about very long setTimeouts. As I need a retry that keeps retrying forever, I will have to use another package. 

Would be nice if that package besides allowing passing timeout a number, if it allowed null or 'INFINITELY' as retries prop has as option. Both wouldn't use setTimeout.

**Comment by normartin** [comment]
Hey Henrique,
I am happy to do this change, but won’t be able to work on it before end of
January as I am on vacation atm.

Btw: I think infinitely should have been the default but that would be a
breaking change.

**Comment by ftzi** [comment]
Thanks for the answer.

I personally don't care about breaking changes if they are in a new semver major. The rule of thumb is that if someone upgrades a package to a new major, this person should read the changelog. But, anyway, I don't think it's **that** important for it to become the default.

I am now using async-retry package to fit my requirement, but honestly I preferred your package. So, no hurry.

Anyway, have a great vacation!

**Comment by normartin** [comment]
Hey @SrBrahma ,
can you have a look at the PR https://github.com/normartin/ts-retry-promise/pull/29 ?

Thanks
Martin

**Comment by normartin** [comment]
Released v0.6.1

**Comment by ftzi** [comment]
Sorry for not yet taking a look, @normartin . I am right now on the final stage of my project and I am really out of time.

But, thanks for adding it!
