### ISSUE TITLE
failing timeout without an error

### ISSUE THREAD

**Issue by rawi123** [normartin/ts-retry-promise#37]
hey ,
will it be possible to get the last error we got after a timeout issue?
i have this simple code (for example)
`const throwErr=async()=>{
  throw new Error("throwed a new error from axios")
}

async function retryIt(){
  try{
    await retry(async ()=>await throwErr(),{
      retries:2,
      delay:1000,
      timeout:3000
    })
  }catch(e){
    console.log(e)
  }
}`
not talking specifically about this timeouts and retries but in general
when getting to the time out im just missing the latest errors, stacks and everything and just getting the timeout from the retry
how can this be fixed?
not related to the issue above, there is a delay even after the last retry, excepted behavior is that there should not be a delay after the last retry

**Comment by robokozo** [comment]
You can get the last error as described here: https://github.com/normartin/ts-retry-promise#failure

**Comment by normartin** [comment]
Thx for answering @robokozo :slightly_smiling_face:
