### ISSUE TITLE
Return last received error instead of generic timeout error

### ISSUE THREAD

**Issue by bennycode** [normartin/ts-retry-promise#41]
I noticed that my wrapped promises fail with the following error (when the ts-retry-promise timeout is hit):

> Error: Timeout after 60000ms
> at Timeout._onTimeout (/node_modules/ts-retry-promise/src/timeout.ts:14:20)

Is it possible to receive the last actual error (returned from an API call) instead of the generic "Timeout after" error?

**Comment by normartin** [comment]
No. Currently the timeout only has access to the "retry promise" and not the internal state of the retry where the lastError lives. I could see if I can make it possible if this would help?

**Comment by bennycode** [comment]
That would be nice, thank you!
