### ISSUE TITLE
NotRetryableError: documentation

### ISSUE THREAD

**Issue by fauxbytes** [normartin/ts-retry-promise#43]
Hi. 
Think [the docs](https://github.com/normartin/ts-retry-promise#notretryableerror) put the config object in the wrong place. Shouldn't it be before the catch block?
Also, passing "This error" to `NotRetryableError`'s ctor suggests to me this data is somehow communicated through to the catcher. Which I think it doesn't.
```
$ cat src/foo.ts
import { NotRetryableError, retry } from "ts-retry-promise";

(async () => {
    await retry(async () => {throw new NotRetryableError("This error")}, {retries: 'INFINITELY'})
        .catch(err => console.log(err.message));
})();

$ ts-node src/foo.ts
Met not retryable error. Last error: NotRetryableError
```

**Comment by normartin** [comment]
Hi @fauxbytes ,
thanks for your your report. Yes the readme is wrong. Also your observations regarding the ctor is correct. Both error types are implemented in a not ideal way. I cannot remember why it was done this way :-|. 

To improve things I added a `message` property to both errors which will make the message accessible later on. Could you have a look at the PR #45  which also fixes the readme?

**Comment by fauxbytes** [comment]
LGTM 🔥🙏🏼

**Comment by normartin** [comment]
Sorry for the long delay. I will release it now.
