### ISSUE TITLE
sourcemap not valid?

### ISSUE THREAD

**Issue by awinograd** [normartin/ts-retry-promise#50]
I'm getting the following error when bundling this library as one of my deps in webpack:
 
> WARNING in ../../../node_modules/ts-retry-promise/dist/retry-promise.js
> Module Warning (from ../../../node_modules/source-map-loader/dist/cjs.js):
> Failed to parse source map from '<...>/node_modules/ts-retry-promise/src/retry-promise.ts' file: Error: ENOENT: no such file or directory, open '<...>/node_modules/ts-retry-promise/src/retry-promise.ts'

The published module doesn't have the `src/` directory even though it's referenced by `retry-promise.js.map`

**Comment by normartin** [comment]
Hey Alec, the `src/` is not included in the package. You are the first one to come up with the issue. I have a potential fix in #51 . Could you verify that this would work for you?

Either by
- Checkout the branch from the PR
- `npm i`
- `npm run build`
- `npm dist`
- In your project, install the package (filename `ts-retry-promise-0.6.0.tgz`) via `npm install path-to-tgz`

or use the tgz I attached.

[ts-retry-promise-0.6.0.tgz](https://github.com/normartin/ts-retry-promise/files/15208380/ts-retry-promise-0.6.0.tgz)

Please also note that the lib has automated tests only for NodeJS and not browsers.

**Comment by awinograd** [comment]
@normartin just downloaded the tgz and can confirm the warnings have been resolved. Thanks for taking a look!
