### ISSUE TITLE
Good one!

### ISSUE THREAD

**Issue by vitaly-t** [normartin/ts-retry-promise#53]
This is a very good solution, it seems! I wish I did a better research before trying to write one of my own a few days ago, but I enjoy challenges, and so I wrote a [code snippet for it here](https://gist.github.com/vitaly-t/6e3d285854d882b1618c7e435df164c4).

I wonder, what do you think about such a shorter solution? Any obvious shortcomings in comparison?

**Comment by normartin** [comment]
Implementation seems ok, from a quick look. Passing in functions instead of values for configuration is more flexible. On the other hand, it also increases cognitive load when reading the code, as we have to analyze the functions.

I'm not happy with all the design decisions in ts-retry-promise, but I want to keep it stable and not break compatibility.

**Comment by vitaly-t** [comment]
Any "async retry" implementation involves a callback function that returns a `Promise`. Otherwise, what are you retrying? :) You need to be able to re-create a `Promise`, that's the core logic of the retry, and for that you need to a create a new `Promise`, hence the callback necessity.

**Comment by normartin** [comment]
Yes, at least one function is required :-). I was referring to the configuration where you pass in 3 additional functions.

```
// our async function, result from which we intend to re-try, when it fails:
async function makeRequest(s: RetryStatus) {
    if (--failCount >= 0) {
        throw new Error(`Request failed ${s.index + 1} time(s)`);
    }
    return `Request succeeded after ${s.duration}ms`;
}

// use delays with 0.5s increments:
const delay = (s: RetryStatus) => (s.index + 1) * 500;

// retry for up to 5 times, with duration not exceeding 4s:
const retry = (s: RetryStatus) => s.index < 5 && s.duration <= 4000;

const error = (s: RetryStatus) => {
    const info = {index: s.index, duration: s.duration, error: s.error.message};
    console. Error('Handling:', info);
}

(function test() {
    retryAsync(makeRequest, {retry, delay, error})
        .then(data => console.log('SUCCESS:', data))
        .catch(err => console.error('FAILED:', err));
})();
```

**Comment by vitaly-t** [comment]
Those functions are all optional, the protocol accepts non-function values also.
