### ISSUE TITLE
Usage as a decorator for function

### ISSUE THREAD

**Issue by sobolevn** [normartin/ts-retry-promise#6]
Hi, thanks a lot for building this awesome tool!

I would like to know, if this is possible to use `retry` as a decorator for existing functions?

Something like this:

```ts
@retry({backoff: 'FIXED'})
export async function doNetworkCall(path: string): Promise<any> { /* ... */ } 
```

**Comment by normartin** [comment]
Hey,
currently it is not possible to use it as a decorator, but I like the idea! I created #7 . This is a decorator without using annotations. 

It works like 

```typescript
import { retryDecorator } from 'ts-retry-promise';

const asyncFunction = async (s: String) => s;

const decorated = retryDecorator(asyncFunction, {timeout: 1});

const result : Promise<string> = decorated("1");
```

What do you think?

**Comment by sobolevn** [comment]
I like it! 👍 

Will it support `@` notation?

**Comment by normartin** [comment]
Unfortunately it will not support the @ notation. It seems like typescript (and JS) decorators cannot be applied to functions ([see](https://stackoverflow.com/questions/37518913/typescript-decorator-for-function-not-method-possible)).

I am not super happy with the name. Any suggestions?

**Comment by normartin** [comment]
#7 is now merged and a new version will be released today

**Comment by sobolevn** [comment]
Awesome, thank you!
